# 1. Create a 3x3x3 array with random values 

In [13]:
import numpy as np
ranArr=np.random.randint(0,777,size=(3,3,3))
ranArr

array([[[442, 525, 412],
        [374, 595, 413],
        [287,  54, 277]],

       [[461, 522,  85],
        [174,   7, 410],
        [475, 491, 473]],

       [[715,  88, 663],
        [ 63, 549, 496],
        [590, 601, 743]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
a=np.diag([1,2,3,4],-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [16]:
print("Checkerboard pattern :- ")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern :- 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [22]:
b= np.random.random((5,5))
print("Before Normalize :-")
print(b,"\n") 
bmax, bmin = b.max(), b.min()
b = (b - bmin)/(bmax - bmin)
print("After Normalize :-")
print(b)

Before Normalize :-
[[0.12376088 0.63602643 0.1926652  0.08146364 0.13213062]
 [0.00847935 0.89583864 0.12133098 0.72635072 0.00724532]
 [0.75219697 0.17977188 0.15005038 0.13518113 0.68523092]
 [0.72320941 0.63602667 0.06054487 0.75954365 0.67634905]
 [0.00602077 0.29399048 0.68539886 0.33794313 0.93895607]] 

After Normalize :-
[[0.12620393 0.67529405 0.20006149 0.08086613 0.13517534]
 [0.00263531 0.95378304 0.12359936 0.77211136 0.00131257]
 [0.79981559 0.18624133 0.15438327 0.13844514 0.72803564]
 [0.76874424 0.67529431 0.0584436  0.80769039 0.71851529]
 [0.         0.30867061 0.72821565 0.35578283 1.        ]]


# 5.  How to find common values between two arrays?

In [25]:
arr1=np.array([2,3,1,8,9])
arr2=np.array([7,1,2,9,5])
print( arr1,"\n",arr2)
print('Common Values are :-',np.intersect1d(arr1,arr2))

[2 3 1 8 9] 
 [7 1 2 9 5]
Common Values are :- [1 2 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [31]:
yesD = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday :-", yesD)
today = np.datetime64('today','D')
print("Today     :-", today)
torow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow  :-",torow)

Yesterday :- 2020-07-27
Today     :- 2020-07-28
Tomorrow  :- 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [41]:
a = np.random.randint(0,9,7)
print("First array:-")
print(a)
b = np.random.randint(0,9,7)
print("Second array:-")
print(b,"\n")
print("Test above two arrays are equal or not!")
array_equal = np.allclose(a,b)
print(array_equal)

First array:-
[5 8 3 1 1 1 6]
Second array:-
[0 5 4 2 7 8 6] 

Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [40]:
x = np.random.random(10)
print("Main Array:-")
print(x,"\n")
x[x.argmax()] = 0
print("Maximum value replaced by 0:-")
print(x)


Main Array:-
[0.81368693 0.30476582 0.52618456 0.83821365 0.40360691 0.07128926
 0.14378751 0.57338773 0.2405014  0.98652346] 

Maximum value replaced by 0:-
[0.81368693 0.30476582 0.52618456 0.83821365 0.40360691 0.07128926
 0.14378751 0.57338773 0.2405014  0.        ]


# 9. How to print all the values of an array?

In [42]:
x = np.ones((7,9))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [44]:

print("Main matrix:\n")
a = np.random.rand(2,3)
print(a)
print("\nSubtract the mean of each row of the said matrix:\n")
b = a - a.mean(axis=1, keepdims=True)
print(b)


Main matrix:

[[0.20353115 0.56869574 0.45078392]
 [0.45660182 0.68968545 0.90271295]]

Subtract the mean of each row of the said matrix:

[[-0.20413912  0.16102547  0.04311365]
 [-0.22639826  0.00668538  0.21971288]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [47]:
a = np.random.randint(5,7,9)
print("Given vector   :-", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:-", b)
print("Result         :-",a)

Given vector   :- [6 5 6 5 5 5 5 5 6]
Indexing vector:- [0 0 0 1 1 1 1 3 3]
Result         :- [7 6 6 6 5 5 5 5 6]


# 12.How to get the diagonal of a dot product?

In [50]:
a = [[7,9],[8,4]]
b = [[9,3],[5,9]]
c = np.diag(np.dot(a,b))
print("Diagonal of Product :-",c)

Diagonal of Product :- [108  60]


# 13.How to find the most frequent value in an array?

In [55]:
arr= np.random.randint(0, 77,69)
print("Main array:-")
print(arr,"\n")
print("Most frequent value in the above array:-",np.bincount(arr).argmax())

Main array:-
[17 71 47 68 52  2  9 75 19 75 26 68 18 10 62  0 62 11 46 59 19 64 50 14
 11 75 57 20 29 69 29 35 72 14 64 28 76 13 26 37 10 37 51 57 22 30  6 30
 45 39 19 29 58 29 10 23 67 35 54 16 52 19 62 45 48 66 41 25  8] 

Most frequent value in the above array:- 19


# 14.How to get the n largest values of an array

In [58]:
a = np.arange(777)
print("Main array :-")
print(a)
np.random.shuffle(a)
b =1
print ("\n Largest Array:-",a[np.argsort(a)[-b:]])

Main array :-
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 

# 15.How to create a record array from a regular array?

In [59]:
a1=np.array(['Virat Kohli','Mahi','Bhumhara ','Sachin','Ab de villiers'])
a2=np.array(['Cristiano Ronaldo','Lional Messi','Mbappe','Sergio Ramos','Rashford'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

('Virat Kohli', 'Cristiano Ronaldo')
('Mahi', 'Lional Messi')
('Bhumhara ', 'Mbappe')
('Sachin', 'Sergio Ramos')
('Ab de villiers', 'Rashford')
